### ISSUE TITLE
Investigate where BLS library breaks 4337 spec

### ISSUE THREAD

**Issue by JohnGuilding** [getwax/wax#137]
When running a transaction via the safe BLS plugin against a bundler, we get the following error when validating the signature:
`account uses banned opcode: GAS`. The error appears to be thrown when `BLS.hashToPoint` is called (other functions may break the spec but this was where the error was noticed).

We should identify what parts of the BLS lib break the 4337 spec, so that the library can be updated.

**Comment by JohnGuilding** [comment]
As part of this investigation, we could try delegate call to an aggregator from the BLS plugin. This may avoid the gas opcode restrictions

**Comment by voltrevo** [comment]
This occurs because in eth-infinitism's copy of `BLS.sol` they're using `gasleft()`:
https://github.com/eth-infinitism/account-abstraction/blob/v0.6.0/contracts/samples/bls/lib/hubble-contracts/contracts/libs/BLS.sol#L65

This compiles to the forbidden opcode `GAS`. There is an exception where `GAS` may be used immediately before a call instruction, but that doesn't happen in the way this code compiles. This simple adjustment has the same intent and causes the compiled code to qualify for the exception:

```solidity
assembly {
    callSuccess := staticcall(
        gas(), // <--- doing it directly in the assembly puts the opcode directly before the call
        8,
        input,
        384,
        out,
        0x20
    )
}
```

Optimizing the variable assignment version into this version technically changes the behavior, which might explain why solidity doesn't do this.

**Comment by voltrevo** [comment]
Having explained the current version, that leaves two questions:
1. What's wrong with the original version that uses `BNPairingPrecompileGasEstimator`?
2. Is it ok not to use `BNPairingPrecompileGasEstimator`? (If it's not needed then why does it exist?)

**Comment by voltrevo** [comment]
> 1. What's wrong with the original version that uses `BNPairingPrecompileGasEstimator`?

This contract allows the BLS lib to call the precompile with an accurate amount of gas. Per [EIP-1108](https://eips.ethereum.org/EIPS/eip-1108), the gas currently needed is `45000 + 34000 * k`, where `k` is basically the size of the input. However, the problem is that future hardforks could change this, which would break the contract if it hardcoded this amount.

`BNPairingPrecompileGasEstimator` solves this problem by measuring the gas used by the precompile with a couple of known valid inputs. It uses these measurements to derive new values for `A` and `B` in the formula `A + B * k`, and exposes a `run()` function so this can be recalculated by anyone at any time, so the lib can be unbroken if the gas usage is changed by a hardfork.

The problem for 4337 is that the stored values `A` and `B` (aka [`baseCost`](https://github.com/thehubbleproject/hubble-contracts/blob/v0.13.1/contracts/libs/BNPairingPrecompileCostEstimator.sol#L5) and [`perPairCost`](https://github.com/thehubbleproject/hubble-contracts/blob/v0.13.1/contracts/libs/BNPairingPrecompileCostEstimator.sol#L6)) violate the storage rules.

**Comment by voltrevo** [comment]
> Is it ok not to use `BNPairingPrecompileGasEstimator`? (If it's not needed then why does it exist?)

Short answer: yes.

The core cryptography utilized by BLS cannot be implemented efficiently directly in the EVM, so this happens in precompile `0x08` introduced by [EIP-197](https://eips.ethereum.org/EIPS/eip-197). The precompile only requires sufficient gas, beyond that it does not need a particular amount of gas to function correctly.

If the precompile returns that the check passed, then the BLS signature is valid.

The problem for the BLS lib is that it wants to support the reverse: proving that a signature is *invalid*.

The idea is to use this for fraud proofs - avoid verifying the sig by allowing people to simply stake a claim that it's valid, and provide a mechanism to prove it's invalid. By using L2s like Optimism and Arbitrum we are also dependent on fraud proofs, but those fraud proofs work by challenging the overall state transition by evaluating the verification code path, and a failure to verify is sufficient to produce a different state even if the signature is valid.

At this point it's important to clarify that any EVM function that produces an explicit bool output actually produces a tri-bool when you consider the call failure case:

```solidity
assembly {
    callSuccess := staticcall( // <--- callSuccess is the success/failure of the *call itself*, not the output
        precompileGasCost,
        8,
        add(input, 0x20),
        mul(inputSize, 0x20),
        out, // <--- this is the explicit boolean output parameter
        0x20
    )
}
```
- https://github.com/thehubbleproject/hubble-contracts/blob/v0.13.1/contracts/libs/BLS.sol#L120-L129

Usually, we eliminate this tri-bool confusion by simply requiring that `callSuccess` is always true, and only use the explicit output. Solidity allows us to do this by interpreting `callSuccess == false` as a propagating exception that causes the entire operation to fail, which we should be able to fix by fixing our input or providing more gas.

Unfortunately, the precompile *fails* under the important condition below instead of returning false:
> If the length of the input is incorrect or any of the inputs are not elements of the respective group or are not encoded correctly, the call fails.
- https://eips.ethereum.org/EIPS/eip-197

This is really painful because:
1. The EVM does not allow us to tell the difference between out-of-gas and 'the call fails'
2. The EVM can't efficiently check that the parameters that are supposed to be in G2 are actually in the G2 group
    - (the precompile does it using fast exponentiation on a complex elliptic curve (not simply modular exponentiation, which we could do using the `0x05` precompile))
    - (the BLS lib provides `isOnCurveG2`, but this only checks that it's on the elliptic curve, which is not enough - it must also be in a special subgroup of that curve, which is not checked)

This lead the BLS lib to make sure that enough gas is passed into the precompile, so that it can disambiguate between invalid input and insufficient gas. The distinction is critical because the former is required for proving fraud, but the latter can be produced artificially (or accidentally) by providing insufficient gas.
