### ISSUE TITLE
Determine format from recovery email

### ISSUE THREAD

**Issue by jacque006** [getwax/wax#170]
*As a* Smart contract account owner using email recovery
*I Would Like To* Know how to write a recovery email
*So I can* Recover my account & understand what will happen when it completes.

### Details
- Consider matching language/terminology already used in ZKEmail project
  - May also want to get design team/UX input
- Make sure it is human readable but also contains technical details
  - What account is being recovered? May not need this.
  - What the new singer/owner will be
    - Could this be an ERC-1271 based contract?
  - Is there an amount of time (timelock) it will take for the recovery to take effect?
### Example
subject: `recover account 0xabc123...` (or ENS/similar)
body:
```text
update signer for account 0xabc123... to 0xdef456...

# Maybe include some better machine readable content as well
-----BEGIN PUBLIC KEY-----
0xdef456...
-----END PUBLIC KEY-----
```

**Comment by JohnGuilding** [comment]
# Proposed initial design:
The following design is inspired from the format in the https://emailwallet.org/ demo.

The important information in the email is the _to_ email address and the _subject_. The _to_ address is the relayer's email address. The _subject_ contains all the technical information needed to perform the recovery. The body of the email is not functional and is just there to inform the user on what is happening.

![Image](https://github.com/getwax/wax/assets/54913924/cc5fb047-5abe-4cb0-a888-02230dbaed23)

## Functional information in the email and other plugin standards/recovery mechanisms:
With our initial safe plugin design, we will need three addresses (account address (i.e. the safe address), the plugin address being recovered, and the new owner address for the plugin). Regarding what information is needed to recover a module via an email with other plugin standards/recovery mechanisms in mind, there is no specific interface/api to abide by.

In the 6900 and 7579 paradigm, you are likely recovering a validator, how the validation is controlled is completely up to the validator developer. So the value being rotated/recovered could be a single address, a public key (think struct or array), or n number of addresses or public keys etc. On recovery in the case of a multisig, you may also want to reset the threshold (say if you did have 3 signers but now you want 5).

So basically there are a lot of ways recovery could be done, and there is no one-size-fits-all approach for how we could structure the functional information in the emails we generate. Based on this, being opinionated seems like a reasonable initial approach.

### Example design with more complicated recovery mechanism:
Subject field in full: `Update owners for plugin 0xA52956234ceDCff0E37c8f2a81C4d7A776f21704 to [0x4A86962379FaAf330ECdC55Ac2d7ABd640267c9D, 0x74a9a08392080e2FcF4F496B9fDf88435FDb9581, 0x601651684300f390786ae06a415855a44e1Bf79D, 0xe238991cE0F4b380A4c66acEd1cdf5A1F824cBe7, 0xFB6F112cD26D5D23fBcDd64673C1AFCFd72Ce94e] on safe 0xd762941BdDc636BDf5160999E6C9Db5e98fDfF05 with a threshold of 3`
![Image](https://github.com/getwax/wax/assets/54913924/7afc6220-7cd1-46f9-8b6a-b853f28ac0e6)

## Example interfaces from other plugin standards:

### ERC6900:
```solidity
    /// @notice Install a plugin to the modular account.
    /// @param plugin The plugin to install.
    /// @param manifestHash The hash of the plugin manifest.
    /// @param pluginInitData Optional data to be decoded and used by the plugin to setup initial plugin data for
    /// the modular account.
    /// @param dependencies The dependencies of the plugin, as described in the manifest.
    /// @param injectedHooks Optional hooks to be injected over permitted calls this plugin may make.
    function installPlugin(
        address plugin,
        bytes32 manifestHash,
        bytes calldata pluginInitData,
        FunctionReference[] calldata dependencies,
        InjectedHook[] calldata injectedHooks
    ) external;

    /// @notice Uninstall a plugin from the modular account.
    /// @param plugin The plugin to uninstall.
    /// @param config An optional, implementation-specific field that accounts may use to ensure consistency
    /// guarantees.
    /// @param pluginUninstallData Optional data to be decoded and used by the plugin to clear plugin data for the
    /// modular account.
    /// @param hookUnapplyData Optional data to be decoded and used by the plugin to clear injected hooks for the
    /// modular account.
    function uninstallPlugin(
        address plugin,
        bytes calldata config,
        bytes calldata pluginUninstallData,
        bytes[] calldata hookUnapplyData
    ) external;
```

### ERC7579:
```solidity
    /**
     * @dev Enables a Validator module on the account.
     * @dev Implement Authorization control of your chosing
     * @param validator The address of the Validator module to enable.
     * @param data any abi encoded further paramters needed
     */
    function installValidator(address validator, bytes calldata data) external;

    /**
     * @dev Disables a Validator Module on the account.
     * @dev Implement Authorization control of your chosing
     * @param validator The address of the Validator module to enable.
     * @param data any abi encoded further paramters needed
     */
    function uninstallValidator(address validator, bytes calldata data) external;

    /**
     * Enable module
     *  This function is called by the MSA during "installValidator, installExecutor, installHook"
     * @dev this function MUST revert on error (i.e. if module is already enabled)
     */
    function onInstall(bytes calldata data) external;

    /**
     * Disable module
     *  This function is called by the MSA during "uninstallValidator, uninstallExecutor, uninstallHook"
     * @dev this function MUST deinitialize the module for the user, so that it can be re-enabled later
     */
    function onUninstall(bytes calldata data) external;
```

## Formatting:

### Feedback on intitial design from design team:
> it’s great you’ve already identified which info is functional and which is purely informative. Next step imo would be to help the user identify the functional info and how they can use it. (this is assuming you already understand the needs of the target audience in this scenario)

> have you played with text hierarchy? idk what limitations you have in terms of formatting within the email but helping the user differentiate what info is important/usable and what info is simply for reference would help a lot. You could try drawing attention to the important text in 3 ways: 
> - repeating it in the body copy
> - listing it under a header that describes its value
> - displaying in a larger font size than the informational text

### Notes on formatting
After looking into formatting a bit further, it might not be possible to format the email beyond plain text and adding emoji's. This is because the emails will probably be generated via a mailto url - https://en.wikipedia.org/wiki/Mailto. Looks like formatting is basically not permitted by the mailto scheme.

Another option might be to ask the user to manually copy some already formatted text and then paste that into an email they create. Although that would be more steps for the user and more prone to human error when copying the functional information. We may want a more manual option anyway in case a user has issues with a mailto url. So maybe this is an option we could go for as well.

**Comment by JohnGuilding** [comment]
## Proposed design as plaintext

**Subject:**
> Update owner for plugin 0xA52956234ceDCff0E37c8f2a81C4d7A776f21704 to 0x4A86962379FaAf330ECdC55Ac2d7ABd640267c9D on safe 0xd762941BdDc636BDf5160999E6C9Db5e98fDfF05

**Body:**
> 🛟 You are recovering an account. This email gives permission to rotate an owner address on a Safe ECDSA Plugin.
>
> 🔑 The new owner address is:                  0x4A86962379FaAf330ECdC55Ac2d7ABd640267c9D
>
>🔌 The plugin that is being recovered is:  0xA52956234ceDCff0E37c8f2a81C4d7A776f21704
>
>💳 The Safe address is:                            0xd762941BdDc636BDf5160999E6C9Db5e98fDfF05
>
>❗Please CHECK the above address values CAREFULLY. This transaction is triggered when you send this email. Don't edit the to: or subject: fields, or else it will fail!
>
>📤 [email@recovery.com](http://sendeth.org/) relays your email on Sepolia testnet to execute the transaction. Expect a confirmation email when finished.
>
>📖 Read more on our site, docs, or code at [https://wax.pse.dev](https://emailwallet.org/)

**Comment by SoraSuegami** [comment]
Hi! I am Sora from ZK Email/Email Wallet team.
Thank you for sharing your work on the email-based account recovery.

> In the 6900 and 7579 paradigm, you are likely recovering a validator, how the validation is controlled is completely up to the validator developer. So the value being rotated/recovered could be a single address, a public key (think struct or array), or n number of addresses or public keys etc. On recovery in the case of a multisig, you may also want to reset the threshold (say if you did have 3 signers but now you want 5).

> So basically there are a lot of ways recovery could be done, and there is no one-size-fits-all approach for how we could structure the functional information in the emails we generate. Based on this, being opinionated seems like a reasonable initial approach.

To generalize the recovery method, I think your protocol might be able to take a similar approach to extensions of Email Wallet.
In a nutshell, an extension contract developed by third-party developers can define expected subject templates using fixed words and some variable templates such as {string}, {uint}, {address}, and so on.
The extension contract can receive the variable data written in the subject from our core contract after it verifies the ZK proof of email.
For example, to allow the recovery email to set five signer addresses and the threshold, the subject template will be `Update owners for plugin {address} to [{address}, {address}, {address}, {address}, {address}] on safe {address} with a threshold of {uint}`. Your contract will receive the actual value of each {address} and {uint} in the subject and set new signers and the threshold to the specified plugin address being recovered.
By updating the subject templates and the functions to handle the given values, the plugin contract can support multiple recovery patterns that the user wants.

This is an example extension code to allow users to swap tokens via Uniswap.
 https://github.com/zkemail/email-wallet/blob/main/packages/contracts/src/extensions/UniswapExtension.sol
 
> After looking into formatting a bit further, it might not be possible to format the email beyond plain text and adding emoji's. This is because the emails will probably be generated via a mailto url - https://en.wikipedia.org/wiki/Mailto. Looks like formatting is basically not permitted by the mailto scheme.

Maybe you can use the following codes to embed emoji to an email from the mailto URL?
https://github.com/zkemail/emailwallet.org/blob/acedeeab0e6e1bacb9066f9699f1308477ad18c1/lib/send.ts#L38-L63

> Another option might be to ask the user to manually copy some already formatted text and then paste that into an email they create.

I personally don't think we should ask the user to manually copy data. If we have to do that, there is room to improve the protocols/specifications.

**Comment by JohnGuilding** [comment]
Thanks for the detailed feedback @SoraSuegami this is really helpful. The extensions code you linked makes sense. I had two follow up questions:

___

> The extension contract can receive the variable data written in the subject from our core contract after it verifies the ZK proof of email.

Given we may have slightly different email subjects, what do these potential differences mean for the implementation of the zk verification itself? (My knowledge of the zk side of things is limited, but my understanding would be that different values in the subject (thinking mainly the different values being rotated/recovered) would lead to different values/types for the public inputs) - Would it add much complexity to writing the circuits?

Some additional concrete examples of different subjects would be:

1. Rotating an ethereum address (type being rotated: `address`)
> Update owner for plugin 0xA52956234ceDCff0E37c8f2a81C4d7A776f21704 to 0x4A86962379FaAf330ECdC55Ac2d7ABd640267c9D on account 0xd762941BdDc636BDf5160999E6C9Db5e98fDfF05

2. Rotating a bls public key (type being rotated: `uint256[4]`)
> Update owner for plugin 0xA52956234ceDCff0E37c8f2a81C4d7A776f21704 to [
  0x004b1d8408dcc643647e4f32a761853e873cd1da8ffc40f03b00647484b3498a,
  0x248b9979254108c9cbb2005739dc693f1694b7b2058942114a0ab4aa81723a6d,
  0x0edd89947147f52246e1dc3092b62c9020afca38d470b3b827e267c66350da93,
  0x2d3f8d5cc58f02219b73b70a0acf33778335e7b5f5c7bf98a1d596b9270e92bb
] on account 0xd762941BdDc636BDf5160999E6C9Db5e98fDfF05

3. Rotating a secp256r1 public key (type being rotated: `uint256[2]`)
> Update owner for plugin 0xA52956234ceDCff0E37c8f2a81C4d7A776f21704 to [
  0x004b1d8408dcc643647e4f32a761853e873cd1da8ffc40f03b00647484b3498a,
  0x248b9979254108c9cbb2005739dc693f1694b7b2058942114a0ab4aa81723a6d
] on account 0xd762941BdDc636BDf5160999E6C9Db5e98fDfF05

_**Note:** After thinking about the multisig example a bit more, it may be an edge case where you would want to recover an entire multisig at once, given the likelihood of losing multiple keys at once is low. A more realistic example would be you may want to rotate an ethereum address in one scenario, and then you may want to rotate a public key in another example, which could take the form of a struct or array._

___

> I personally don't think we should ask the user to manually copy data. If we have to do that, there is room to improve the protocols/specifications.

I agree manually copying data is not optimal. Formatting aside, do you think having a backup option to copy the email data is a worthwhile feature? Reason I ask is that the email wallet demo does appear to have that as a feature: 

![Image](https://github.com/getwax/wax/assets/54913924/84f98bd0-5fd2-43d8-bf5b-0b9e1a957d5d)

I was assuming this would act as a backup option in case the user faced any difficulties with the mailto link. A possible edge case may be that a user's default email client is not actually the email they want to use.

**Comment by SoraSuegami** [comment]
> Given we may have slightly different email subjects, what do these potential differences mean for the implementation of the zk verification itself? (My knowledge of the zk side of things is limited, but my understanding would be that different values in the subject (thinking mainly the different values being rotated/recovered) would lead to different values/types for the public inputs) - Would it add much complexity to writing the circuits?

If we use a circuit that exposes the whole string in the subject, public inputs corresponding to the exposed subject are different among the subject formats. In other words, the verifying key and the verifier contract are the same. Therefore, multiple subject formats increase only the complexity of contracts for computing the public inputs from the user's inputs.

I expect that specifying the subject format inside the circuit increases not only the number of verifier contracts but also the number of circuit constraints, i.e., the proving time, because more complex constraints for the regex verification are necessary.

 > Formatting aside, do you think having a backup option to copy the email data is a worthwhile feature? Reason I ask is that the email wallet demo does appear to have that as a feature:
 
 Sorry, I misunderstood why you think an option to copy the email data.
 Yes, we prepared the copy option for users facing difficulties with the mailto link.

**Comment by jacque006** [comment]
Closing initial design as complete. Tweaks can still be made as follow up.
